### ISSUE TITLE
fullscreen on our own container

### ISSUE THREAD

**Issue by cvan** [KevinGrandon/EtherWorld#78]
from @caseyyee:

> ah ok, yeah.  so to do that, comment out: node_modules/voxel-engine/node_modules/interact/index.js    comment out line 14 `, rfs = shim(el)`

**Comment by caseyyee** [comment]
Fixed the weird mouse capture issues with 3eaf3fffec3d0278a071b286f2a562094be2b16a

**Comment by cvan** [comment]
thanks, man
